backend/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from account.views import (
    request_user,
    payment_callback,
    recover_password,
    SettingsUserView,
)


app_name = 'account'


urlpatterns = [

    path('request-user/', request_user, name='request_user'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('recover-password/', recover_password, name='recover_password'),

    path('payment-callback/', payment_callback, name='payment_callback'),

    path('lk/settings-user/', SettingsUserView.as_view(), name='settings_user'),

]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [

    path('', include('account.urls')),

    path('', include('public_side.urls')),

    path('lk/', include('private_side.urls')),

    path('admin/', admin.site.urls),

]

handler404 = TemplateView.as_view(template_name='public/not-found.html')

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/chat/urls.py
from django.urls import path


urlpatterns = [
]

backend/private_side/urls.py
from django.urls import path, include

from .views import (
    IndexLkView,
    FreeLessonView,
    StudentsListView,
)


app_name = 'private_side'


urlpatterns = [
    path('', IndexLkView.as_view(), name='index'),

    path('free-lesson/', FreeLessonView.as_view(), name='free_lesson'),
    path('students/', StudentsListView.as_view(), name='students'),

    path('', include('course.urls')),
    path('', include('paid_course.urls')),

    # path('', include('lesson.urls')),
]

backend/public_side/urls.py
from django.urls import path
from django.views.generic import TemplateView

from account.views import AccountLoginView


app_name = 'public_side'


urlpatterns = [
    path('', AccountLoginView.as_view(), name='index'),

    path('process/', TemplateView.as_view(template_name='public/process.html'), name='process'),
    path('faq/', TemplateView.as_view(template_name='public/faq.html'), name='faq'),
    path('price/', TemplateView.as_view(template_name='public/price.html'), name='price'),
    path('about/', TemplateView.as_view(template_name='public/about.html'), name='about'),
    # path('teachers/', TemplateView.as_view(template_name='public/teachers.html'), name='teachers'),
    path('testimonials/', TemplateView.as_view(template_name='public/testimonials.html'), name='testimonials'),
    path('contacts/', TemplateView.as_view(template_name='public/contacts.html'), name='contacts'),
    path('contract_offer/', TemplateView.as_view(template_name='public/contract_offer.html'), name='contract_offer'),
]

backend/chat/models.py
from django.contrib.auth import get_user_model
from django.db import models

from common.models import CommonId


class Chat(CommonId):
    interlocutor_one = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='chat_interlocutor_one', verbose_name='первый собеседник')
    interlocutor_two = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='chat_interlocutor_two', verbose_name='второй собеседник')

    @property
    def last_message(self):
        return self.message_set.last()

    def __str__(self):
        return f'{self.interlocutor_one} | {self.interlocutor_two}'

    class Meta:
        verbose_name = 'чат'
        verbose_name_plural = 'чаты'
        unique_together = ('interlocutor_one', 'interlocutor_two')


class Message(CommonId):
    text = models.TextField(default='', blank=True, verbose_name='текст сообщения')

    sent_at = models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')

    chat = models.ForeignKey('Chat', on_delete=models.PROTECT, verbose_name='чат')
    sender = models.ForeignKey(get_user_model(), on_delete=models.PROTECT, related_name='message_sender', verbose_name='отправитель')

    def __str__(self):
        return f'{self.sender} | {self.sent_at}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ('sent_at', )

backend/course/models.py
from django.db import models

from common.models import CommonId, CommonFields
from lesson.models import Lesson


class GroupsOfCourses(CommonFields):

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'группа курсов'
        verbose_name_plural = '01 | Группы курсов'
        ordering = ('title', )


class PackageOfLessons(models.Model):

    count = models.PositiveSmallIntegerField(verbose_name='количество занятий')
    cost = models.PositiveSmallIntegerField(verbose_name='стоимость')

    @property
    def get_count_lessons(self):
        remainder = self.count % 10
        if self.count in (11, 12, 13, 14):
            string = f'{self.count} занятий'
        elif remainder == 1:
            string = f'{self.count} занятие'
        elif remainder in (2, 3, 4):
            string = f'{self.count} занятия'
        else:
            string = f'{self.count} занятий'
        return string

    def __str__(self) -> str:
        return f'{self.get_count_lessons} | {self.cost}'

    class Meta:
        verbose_name = 'количество занятий'
        verbose_name_plural = '02 | Количество занятий'
        ordering = ('count', 'cost')


class Course(CommonFields):

    is_published = models.BooleanField(default=False, verbose_name='опубликован')

    group_of_course = models.ForeignKey(GroupsOfCourses, on_delete=models.PROTECT, verbose_name='группа курса')

    image = models.ImageField(upload_to='img/course/', default='img/course/default.jpg', verbose_name='изображение курса')

    package_of_lessons = models.ManyToManyField(PackageOfLessons, related_name='courses', verbose_name='пакеты занятий')
    lessons = models.ManyToManyField(Lesson, through='CourseLesson', related_name='courses', verbose_name='уроки')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = '03 | Курсы'
        ordering = ('title', )


class Level(CommonFields):

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'уровень'
        verbose_name_plural = '04 | Уровни'
        ordering = ('title', )


class CourseLesson(CommonId):

    number = models.PositiveSmallIntegerField(verbose_name='номер урока')

    course = models.ForeignKey(Course, on_delete=models.PROTECT, verbose_name='курс')
    lesson = models.ForeignKey(Lesson, on_delete=models.PROTECT, verbose_name='урок')
    level = models.ForeignKey(Level, on_delete=models.PROTECT, verbose_name='уровень')

    def __str__(self):
        return f'{self.course} | {self.number} {self.lesson}'

    class Meta:
        verbose_name = 'уроки курсов'
        verbose_name_plural = '05 | Уроки курсов'
        ordering = ('number', )

backend/templates/private/components/chat.html
<div>
  <p>What chat room would you like to enter?</p>
  <label for="room-name-input">Room name</label>
  <input id="room-name-input" type="text" size="100"><br>

  <input id="room-name-submit" type="button" value="Enter">
</div>

<script>
  document.querySelector('#room-name-input').focus();
  document.querySelector('#room-name-input').onkeyup = function(e) {
    if (e.keyCode === 13) {  // enter, return
      document.querySelector('#room-name-submit').click();
    }
  };

  document.querySelector('#room-name-submit').onclick = function(e) {
    const roomName = document.querySelector('#room-name-input').value;
    window.location.pathname = '/chat/' + roomName + '/';
  };
</script>


<label for="chat-log">Чат-лог</label>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<label for="chat-message-input">Сообщение</label>
<input id="chat-message-input" type="text" size="100"><br>

<input id="chat-message-submit" type="button" value="Send">

{{ room_name|json_script:"room-name" }}

<script>
  {#const roomName = JSON.parse(document.getElementById('room-name').textContent);#}
  const roomName = 'one'

  const chatSocket = new WebSocket(
    'ws://'
    + window.location.host
    + '/ws/chat/'
    + roomName
    + '/'
  );

  chatSocket.onmessage = function(e) {
    const data = JSON.parse(e.data);
    document.querySelector('#chat-log').value += (data.message + '\n');
  };

  chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
  };

  document.querySelector('#chat-message-input').focus();
  document.querySelector('#chat-message-input').onkeyup = function(e) {
    if (e.keyCode === 13) {  // enter, return
      document.querySelector('#chat-message-submit').click();
    }
  };

  document.querySelector('#chat-message-submit').onclick = function(e) {
    const messageInputDom = document.querySelector('#chat-message-input');
    const message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
      'message': message
    }));
    messageInputDom.value = '';
  };
</script>

backend/templates/private/components/header.html
{% load static %}

<header class="header header-second">
  <div class="wrapper">
    <div class="header-bar">
      <div class="header-bar__1">
        <svg width="27" height="27" viewBox="0 0 27 27" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M3.375 7.875C3.375 7.25368 3.87868 6.75 4.5 6.75H22.5C23.1213 6.75 23.625 7.25368 23.625 7.875C23.625 8.49632 23.1213 9 22.5 9H4.5C3.87868 9 3.375 8.49632 3.375 7.875ZM3.375 13.5C3.375 12.8787 3.87868 12.375 4.5 12.375H22.5C23.1213 12.375 23.625 12.8787 23.625 13.5C23.625 14.1213 23.1213 14.625 22.5 14.625H4.5C3.87868 14.625 3.375 14.1213 3.375 13.5ZM3.375 19.125C3.375 18.5037 3.87868 18 4.5 18H22.5C23.1213 18 23.625 18.5037 23.625 19.125C23.625 19.7463 23.1213 20.25 22.5 20.25H4.5C3.87868 20.25 3.375 19.7463 3.375 19.125Z" fill="#2F2F2F"></path>
        </svg>
      </div>
      <div class="header-bar__2">
        <svg viewBox="0 0 24 24" width="24" height="24">
          <path d="m 19.071068,4.9289322 a 1,1 0 0 0 -1.414214,0 L 12,10.585786 6.3431458,4.9289322 a 1,1 0 0 0 -1.4142136,0 1,1 0 0 0 0,1.4142136 L 10.585786,12 4.9289322,17.656854 a 1,1 0 0 0 0,1.414214 1,1 0 0 0 1.4142136,0 L 12,13.414214 l 5.656854,5.656854 a 1,1 0 0 0 1.414214,0 1,1 0 0 0 0,-1.414214 L 13.414214,12 19.071068,6.3431458 a 1,1 0 0 0 0,-1.4142136 z"></path>
        </svg>
      </div>
    </div>
    <div class="header-logo">
      <a href="{% url 'public_side:index' %}">
        <img src="{% static 'img/logo.svg' %}" alt="">
      </a>
    </div>
    <div class="header-lk">
      <div class="header-link">
{#        <a href="#" class="header-ico">#}
          <svg width="25" height="20" viewBox="0 0 25 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M21.875 0H3.125C2.29647 0.000902401 1.50213 0.336419 0.91627 0.93293C0.330411 1.52944 0.000886287 2.33822 0 3.18182V16.8182C0.000886287 17.6618 0.330411 18.4706 0.91627 19.0671C1.50213 19.6636 2.29647 19.9991 3.125 20H21.875C22.7035 19.9991 23.4979 19.6636 24.0837 19.0671C24.6696 18.4706 24.9991 17.6618 25 16.8182V3.18182C24.9991 2.33822 24.6696 1.52944 24.0837 0.93293C23.4979 0.336419 22.7035 0.000902401 21.875 0ZM21.0837 5.26307L13.048 11.6267C12.8913 11.7507 12.6985 11.8181 12.5 11.8181C12.3015 11.8181 12.1087 11.7507 11.952 11.6267L3.91629 5.26307C3.82188 5.19047 3.74258 5.0995 3.683 4.99543C3.62342 4.89136 3.58474 4.77627 3.56922 4.65685C3.5537 4.53743 3.56165 4.41607 3.5926 4.2998C3.62354 4.18353 3.67688 4.07469 3.7495 3.97959C3.82212 3.88449 3.91257 3.80504 4.01561 3.74585C4.11865 3.68665 4.23222 3.6489 4.34971 3.63478C4.46721 3.62066 4.58628 3.63045 4.70003 3.6636C4.81377 3.69674 4.91991 3.75257 5.01228 3.82784L12.5 9.75739L19.9877 3.82784C20.175 3.68388 20.4103 3.62073 20.6429 3.65207C20.8755 3.68341 21.0866 3.8067 21.2307 3.9953C21.3747 4.18389 21.44 4.42262 21.4125 4.65986C21.385 4.89711 21.2669 5.1138 21.0837 5.26307Z" fill="#6B6B6B"></path>
          </svg>
{#        </a>#}
      </div>
      <div class="header-user">
        <div class="header-user__top">

          <div class="header-user__img">
            <img
              src="{{ account.avatar.url }}"
              alt="{{ account.avatar.title }}"
              width="56px"
              height="56px"
            >
          </div>

          <span class="header-user__name">{{ user.first_name }}</span>
          <span class="header-user__arrow">
            <svg width="8" height="5" viewBox="0 0 8 5" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M6.70226 0.206848L3.95393 2.95518L1.2056 0.206848C1.14002 0.141269 1.06217 0.0892495 0.976483 0.0537585C0.8908 0.0182675 0.798965 6.90987e-10 0.706223 0C0.61348 -6.90983e-10 0.521646 0.0182675 0.435963 0.0537585C0.35028 0.0892495 0.272427 0.141269 0.206848 0.206848C0.141269 0.272427 0.0892492 0.35028 0.0537582 0.435963C0.0182671 0.521646 -6.90984e-10 0.613481 0 0.706223C6.90986e-10 0.798966 0.0182671 0.8908 0.0537582 0.976483C0.0892492 1.06217 0.141269 1.14002 0.206848 1.2056L3.4581 4.45685C3.73435 4.7331 4.1806 4.7331 4.45685 4.45685L7.7081 1.2056C7.77376 1.14007 7.82586 1.06223 7.8614 0.97654C7.89695 0.890851 7.91524 0.798992 7.91524 0.706223C7.91524 0.613454 7.89695 0.521595 7.8614 0.435906C7.82586 0.350216 7.77376 0.272379 7.7081 0.206848C7.43185 -0.0623186 6.97851 -0.0694019 6.70226 0.206848Z" fill="#6B6B6B"></path>
            </svg>
          </span>
        </div>
        <div class="header-drop">
          <ul>
            <li><a href="{% url 'account:settings_user' %}">Настройки профиля</a></li>
            <li><a href="{% url 'account:logout' %}">Выход</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

backend/templates/private/components/left_menu.html
{% load static %}

<div class="menu">
  <div class="menu-arrow">
    <svg width="10" height="16" viewBox="0 0 10 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M7.78 5.68804e-05L9.19 1.42006L2.83 7.78006L9.19 14.1401L7.78 15.5601L-3.40075e-07 7.78006L7.78 5.68804e-05Z" fill="#6B6B6B"></path>
    </svg>
  </div>
  <div class="menu-over">
    <div class="menu-wrap">
      <div class="menu-bg">
        <img src="{% static 'img/menu-bg.svg' %}" alt="">
      </div>


      <ul class="menu-list">

        {% url 'private_side:index' as index_url %}
        <li>
          <a href="{% url 'private_side:index' %}" {% if index_url == request.get_full_path %}class="active"{% endif %}>
            <b class="menu-ico"><img src="{% static 'img/menu-ico-1.svg' %}" width="32" height="32" alt=""></b>
            <span>Личный кабинет</span>
          </a>
        </li>

        {% url 'private_side:timetables' as timetables_url %}
        <li>
          <a href="{{ timetables_url }}" {% if timetables_url == request.get_full_path %}class="active"{% endif %}>
            <b class="menu-ico"><img src="{% static 'img/menu-ico-2.svg' %}" width="32" height="32" alt=""></b>
            <span>Расписание</span>
          </a>
        </li>

        {% url 'private_side:lessons' as lessons_url %}
        <li>
          <a href="{{ lessons_url }}" class="{% if lessons_url == request.get_full_path %}active{% endif %}">
            <b class="menu-ico"><img src="{% static 'img/menu-ico-6.svg' %}" alt=""></b>
            <span>Занятия</span>
          </a>
        </li>

        {% if user.is_staff %}
          {% include 'private/components/teacher_menu.html' %}
        {% else %}
          {% include 'private/components/student_menu.html' %}
        {% endif %}

      </ul>

      {#      {% if not user.is_staff %}#}
      {#        <div class="menu-row">#}
      {#          <a href="#" class="menu-col">#}
      {#            <b class="menu-ico"><img src="{% static 'img/menu-ico-11.svg' %}" alt=""></b>#}
      {#            <span>домашние задания</span>#}
      {#          </a>#}
      {#          <a href="#" class="menu-col">#}
      {#            <b class="menu-ico"><img src="{% static 'img/menu-ico-12.svg' %}" alt=""></b>#}
      {#            <span>План занятий</span>#}
      {#          </a>#}
      {#        </div>#}
      {#      {% endif %}#}

      <div id="chat"></div>

      <div class="menu-footer">

        <div class="menu-footer__bg">
          <img src="{% static 'img/menu-footer__bg.svg' %}" alt="">
        </div>

        {% include 'public/components/footer_social.html' %}

        <div class="menu-footer__bottom">
          <a href="{% url 'public_side:index' %}">
            <img src="{% static 'img/footer-logo.svg' %}" alt="">
          </a>
          <p>Все права защищены. 2020</p>
        </div>
      </div>
    </div>
  </div>
</div>

backend/templates/private/components/online_indicator.html
{% load static %}

<div class="online-indicator">
  <span>Offline</span>
  <div class="online-indicator__wrapper">
    <div class="in-bounce1"></div>
    <div class="in-bounce2"></div>
  </div>
</div>

backend/templates/private/components/student_menu.html
{% load static %}

{% url 'private_side:courses' as courses_url %}
<li>
  <a href="{{ courses_url }}" {% if courses_url == request.get_full_path %}class="active"{% endif %}>
    <b class="menu-ico"><img src="{% static 'img/menu-ico-3.svg' %}" width="32" height="32" alt=""></b>
    <span>Курсы</span>
  </a>
</li>

{#{% url 'private_side:notes' as notes_url %}#}
{#<li>#}
{#  <a href="{% url 'private_side:notes' %}" class="{% if notes_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-4.svg' %}" alt=""></b>#}
{#    <span>Мои заметки</span>#}
{#  </a>#}
{#</li>#}

{#{% url 'private_side:vocabulary_list' as vocabulary_list_url %}#}
{#<li>#}
{#  <a href="{% url 'private_side:vocabulary_list' %}" class="{% if vocabulary_list_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-5.svg' %}" alt=""></b>#}
{#    <span>Мой словарь</span>#}
{#  </a>#}
{#</li>#}

{#{% url 'private_side:tests_courses_list' as tests_courses_list_url %}#}
{#<li>#}
{#  <a href="{% url 'private_side:tests_courses_list' %}" class="{% if tests_courses_list_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-7.svg' %}" alt=""></b>#}
{#    <span>Тесты</span>#}
{#  </a>#}
{#</li>#}

{#<li>#}
{#  <a href="#">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-8.svg' %}" alt=""></b>#}
{#    <span>Словарные игры</span>#}
{#  </a>#}
{#</li>#}

{% url 'private_side:free_lesson' as free_lesson_url %}
<li>
  <a href="{{ free_lesson_url }}" {% if free_lesson_url == request.get_full_path %}class="active"{% endif %}>
    <b class="menu-ico"><img src="{% static 'img/menu-ico-10.svg' %}" width="32" height="32" alt=""></b>
    <span>Бесплатные уроки<i>Пригласить друзей</i></span>
  </a>
</li>

backend/templates/private/components/teacher_menu.html
{% load static %}

{#{% url 'private_side:materials' as materials_url %}#}
{#<li class="menu-li">#}
{#  <a href="{% url 'private_side:materials' %}" class="{% if materials_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-13.svg' %}" alt=""></b>#}
{#    <span>Материалы</span>#}
{#  </a>#}
{#</li>#}

{#{% url 'private_side:tasks' as tasks_url %}#}
{#<li>#}
{#  <a href="{% url 'private_side:tasks' %}" class="{% if tasks_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-15.svg' %}" alt=""></b>#}
{#    <span>Задания</span>#}
{#  </a>#}
{#</li>#}

{#{% url 'private_side:articles' as articles_url %}#}
{#<li>#}
{#  <a href="{% url 'private_side:articles' %}" class="{% if articles_url == request.get_full_path %}active{% endif %}">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-16.svg' %}" alt=""></b>#}
{#    <span>Статьи</span>#}
{#  </a>#}
{#</li>#}
{##}
{#<li>#}
{#  <a href="#">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-17.svg' %}" alt=""></b>#}
{#    <span>Файлы</span>#}
{#  </a>#}
{#</li>#}
{##}
{#<li>#}
{#  <a href="#">#}
{#    <b class="menu-ico"><img src="{% static 'img/menu-ico-18.svg' %}" alt=""></b>#}
{#    <span>Темы</span>#}
{#  </a>#}
{#</li>#}

<li>
  <a href="{% url 'private_side:students' %}">
    <b class="menu-ico"><img src="{% static 'img/menu-ico-19.svg' %}" width="32" height="32" alt=""></b>
    <span>Ученики</span>
  </a>
</li>