backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [

    path('', include('account.urls')),

    path('', include('public_side.urls')),

    path('lk/', include('private_side.urls')),

    path('admin/', admin.site.urls),

]

handler404 = TemplateView.as_view(template_name='public/not-found.html')

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/chat/urls.py
from django.urls import path


urlpatterns = [
]

backend/course/urls.py
from django.urls import path

from .views import (
    CourseListView,
    CourseDetailView,
    TestsCoursesListView,
    TestsCourseLessonListView,
    TasksView,
)


urlpatterns = [
    path('courses/', CourseListView.as_view(), name='courses'),
    path('course/<uuid:pk>', CourseDetailView.as_view(), name='course_detail'),

    # path('tests/', TestsCoursesListView.as_view(), name='tests_courses_list'),
    # path('tests/<uuid:pk>', TestsCourseLessonListView.as_view(), name='tests_lesson_list'),
    #
    # path('tasks/', TasksView.as_view(), name='tasks'),
]

backend/lesson/urls.py
from django.urls import path

from .views import (
    MaterialsListView,
    ArticlesListView,
)


urlpatterns = [
    path('materials/', MaterialsListView.as_view(), name='materials'),
    path('articles/', ArticlesListView.as_view(), name='articles'),
]

backend/private_side/urls.py
from django.urls import path, include

from .views import (
    IndexLkView,
    FreeLessonView,
    StudentsListView,
)


app_name = 'private_side'


urlpatterns = [
    path('', IndexLkView.as_view(), name='index'),

    path('free-lesson/', FreeLessonView.as_view(), name='free_lesson'),
    path('students/', StudentsListView.as_view(), name='students'),

    path('', include('course.urls')),
    path('', include('paid_course.urls')),

    # path('', include('lesson.urls')),
]

backend/course/models.py
from django.db import models

from common.models import CommonId, CommonFields
from lesson.models import Lesson


class GroupsOfCourses(CommonFields):

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'группа курсов'
        verbose_name_plural = '01 | Группы курсов'
        ordering = ('title', )


class PackageOfLessons(models.Model):

    count = models.PositiveSmallIntegerField(verbose_name='количество занятий')
    cost = models.PositiveSmallIntegerField(verbose_name='стоимость')

    @property
    def get_count_lessons(self):
        remainder = self.count % 10
        if self.count in (11, 12, 13, 14):
            string = f'{self.count} занятий'
        elif remainder == 1:
            string = f'{self.count} занятие'
        elif remainder in (2, 3, 4):
            string = f'{self.count} занятия'
        else:
            string = f'{self.count} занятий'
        return string

    def __str__(self) -> str:
        return f'{self.get_count_lessons} | {self.cost}'

    class Meta:
        verbose_name = 'количество занятий'
        verbose_name_plural = '02 | Количество занятий'
        ordering = ('count', 'cost')


class Course(CommonFields):

    is_published = models.BooleanField(default=False, verbose_name='опубликован')

    group_of_course = models.ForeignKey(GroupsOfCourses, on_delete=models.PROTECT, verbose_name='группа курса')

    image = models.ImageField(upload_to='img/course/', default='img/course/default.jpg', verbose_name='изображение курса')

    package_of_lessons = models.ManyToManyField(PackageOfLessons, related_name='courses', verbose_name='пакеты занятий')
    lessons = models.ManyToManyField(Lesson, through='CourseLesson', related_name='courses', verbose_name='уроки')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = '03 | Курсы'
        ordering = ('title', )


class Level(CommonFields):

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'уровень'
        verbose_name_plural = '04 | Уровни'
        ordering = ('title', )


class CourseLesson(CommonId):

    number = models.PositiveSmallIntegerField(verbose_name='номер урока')

    course = models.ForeignKey(Course, on_delete=models.PROTECT, verbose_name='курс')
    lesson = models.ForeignKey(Lesson, on_delete=models.PROTECT, verbose_name='урок')
    level = models.ForeignKey(Level, on_delete=models.PROTECT, verbose_name='уровень')

    def __str__(self):
        return f'{self.course} | {self.number} {self.lesson}'

    class Meta:
        verbose_name = 'уроки курсов'
        verbose_name_plural = '05 | Уроки курсов'
        ordering = ('number', )

backend/lesson/models/article.py
from django.db import models

from common.models import CommonFields


class Article(CommonFields):

    url = models.URLField(blank=True, verbose_name='ссылка на статью')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = '06 | Статьи'

backend/lesson/models/book.py
from django.db import models

from common.models import CommonFields


class Book(CommonFields):

    author = models.CharField(max_length=100, default='', blank=True, verbose_name='автор')
    isbn = models.CharField(max_length=13, default='', blank=True, verbose_name='ISBN')

    def __str__(self):
        return f'{self.title} | {self.author}'

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = '05 | Книги'

backend/lesson/models/test.py
from django.db import models
import random

from common.models import CommonId


class Test(CommonId):

    question = models.CharField(max_length=200, verbose_name='вопрос')
    options = models.CharField(max_length=200, verbose_name='варианты ответа')
    answer = models.CharField(max_length=200, verbose_name='ответ')

    def get_options(self):
        options = self.options.split(', ')
        options.append(self.answer)
        random.shuffle(options)
        return options

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'тест'
        verbose_name_plural = '04 | Тесты'

backend/lesson/models/word.py
from django.db import models

from common.models import CommonId


class Word(CommonId):

    spelling = models.CharField(max_length=200, verbose_name='написание')
    transcription = models.CharField(max_length=200, blank=True, verbose_name='произношение')
    translation = models.CharField(max_length=200, verbose_name='перевод')
    description = models.CharField(max_length=200, blank=True, verbose_name='описание')

    examples = models.ManyToManyField('Example', blank=True, related_name='words', verbose_name='пример со словом')


    def __str__(self):
        return f'{self.spelling.capitalize()} | {self.translation.capitalize()}'

    class Meta:
        verbose_name = 'слово'
        verbose_name_plural = '02 | Слова'


class Example(CommonId):

    example = models.CharField(max_length=200, verbose_name='пример')
    description = models.CharField(max_length=200, blank=True, verbose_name='описание')

    def __str__(self):
        return self.example

    class Meta:
        verbose_name = 'пример со словом'
        verbose_name_plural = '03 | Примеры со словом'

backend/course/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import ProcessFormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse

from course.models import Course, CourseLesson


class CourseListView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'private/courses.html'

    def get_queryset(self):
        return super().get_queryset().filter(
            is_published=True,
        )


class CourseDetailView(LoginRequiredMixin, DetailView):
    model = Course
    template_name = 'private/course_detail.html'


class TestsCoursesListView(LoginRequiredMixin, ListView):
    model = CourseLesson
    template_name = 'private/tests_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(
            course__student__user=self.request.user,
            course__finished=False,
        )


class TestsCourseLessonListView(LoginRequiredMixin, DetailView, ProcessFormView):
    model = CourseLesson
    template_name = 'private/test_detail.html'

    def get_queryset(self):

        return super().get_queryset().filter(
            course__student__user=self.request.user,
            course__finished=False,
        )

    def post(self, request, *args, **kwargs):

        result = {key: value for key, value in request.POST.items() if key != 'csrfmiddlewaretoken'}
        course_lesson = self.get_object()
        tests = course_lesson.lesson.homework_tests.all()
        count_tests = tests.count()

        sum_true_result = 0

        for key, value in result.items():

            if tests.get().answer == value:
                sum_true_result += 1

        course_lesson.test_result = sum_true_result / count_tests
        course_lesson.save()

        return redirect(reverse('private_side:tests_courses_list'))


class TasksView(LoginRequiredMixin, TemplateView):
    template_name = 'private/tasks.html'

backend/lesson/views.py
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Lesson, Article


class MaterialsListView(LoginRequiredMixin, ListView):
    model = Lesson
    template_name = 'private/materials.html'


class ArticlesListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = 'private/articles_list.html'

backend/templates/private/_base.html
{% load static private_side_extras %}

<!DOCTYPE html>
<html lang="ru">
<head>

  {% include 'common/head.html' %}

  <title>{% block title %}Личный кабинет | Hello Panda{% endblock %}</title>
  <meta property="og:title" content="{% block og_title %}{% endblock %}" />

  <meta name="description" content="{% block description %}{% endblock %}" />

</head>
<body class="bodyLk">

{% include 'private/components/header.html' %}

<section class="personalArea personalArea-active"> <!-- Левое меню скрыто (personalArea-active)-->

  {% include 'private/components/left_menu.html' %}

  {% block content %}{% endblock %}

</section>

<div id="snackbar"></div>

{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>#}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://api.fondy.eu/static_common/v1/checkout/ipsp.js"></script>

{% block script %}{% endblock %}

<script src="{% static 'js/main_private.js' %}"></script>

{{ user.pk|json_script:'currentUserId' }}
{{ 'DEBUG'|get_settings_var|json_script:'DEBUG' }}
{{ 'MERCHANT_ID'|get_settings_var|json_script:'MERCHANT_ID' }}

<script>
  const currentUserId = JSON.parse(document.getElementById('currentUserId').textContent)
</script>

<script>
  // Fondy
  const DEBUG = JSON.parse(document.getElementById('DEBUG').textContent)
  const MERCHANT_ID = JSON.parse(document.getElementById('MERCHANT_ID').textContent)

  function createOrder(paid_for_lessons, amount, course_id) {

    const button = $ipsp.get('button')
    button.setMerchantId(MERCHANT_ID)
    button.setAmount(amount, 'UAH', !DEBUG)
    button.setResponseUrl(`${window.location.origin}/payment-callback/`)
    button.setHost('api.fondy.eu')
    button.addField({
      label: 'Промо код',
      name: 'bonus_id'
    })
    button.addField({
      label: 'Количество занятий',
      name: 'paid_for_lessons',
      value: `${paid_for_lessons}`,
      readonly: true
    })
    button.addField({
      label: 'ID Ученика',
      name: 'student_id',
      value: `{{ user.student.pk }}`,
      readonly: true,
      hidden: true
    })
    button.addField({
      label: 'ID курса',
      name: 'course_id',
      value: `${course_id}`,
      readonly: true,
      hidden: true
    })
    window.open(button.getUrl())
    return false
  }

  // Reschedule lesson
  const client = axios.create({
    baseURL: `${window.location.origin}/lk/`,
    contentType: 'application/json; charset=utf-8',
    withCredentials: true,
    xsrfCookieName: 'csrftoken',
    xsrfHeaderName: 'X-CSRFToken',
  })

</script>

</body>
</html>

backend/templates/private/articles_list.html
{% extends './_base.html' %}

{% load static %}

{% block title %}Статьи{% endblock %}

{% block content %}
  <div class="personalArea-content">
    <div class="personalArea-block">
      <div class="personalArea-block__top">
        <span class="personalArea-block__title">Статьи</span>
        <div class="personalArea-block__top-b"></div>
      </div>
      <div class="materials">
        <div class="materials-wrap">
          <div class="materials-block scrollbar-outer">
            <ul>

              {% for article in object_list %}

                <li><a href="{{ article.url }}">
                  <svg width="20" height="12" viewBox="0 0 20 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.0156 0.984375C16.3906 0.984375 17.5625 1.48438 18.5312 2.48438C19.5 3.45312 19.9844 4.625 19.9844 6C19.9844 7.375 19.5 8.5625 18.5312 9.5625C17.5625 10.5312 16.3906 11.0156 15.0156 11.0156H10.9844V9.09375H15.0156C15.8594 9.09375 16.5781 8.79688 17.1719 8.20312C17.7969 7.57812 18.1094 6.84375 18.1094 6C18.1094 5.15625 17.7969 4.4375 17.1719 3.84375C16.5781 3.21875 15.8594 2.90625 15.0156 2.90625H10.9844V0.984375H15.0156ZM6.01562 6.98438V5.01562H13.9844V6.98438H6.01562ZM2.78125 3.84375C2.1875 4.4375 1.89062 5.15625 1.89062 6C1.89062 6.84375 2.1875 7.57812 2.78125 8.20312C3.40625 8.79688 4.14062 9.09375 4.98438 9.09375H9.01562V11.0156H4.98438C3.60938 11.0156 2.4375 10.5312 1.46875 9.5625C0.5 8.5625 0.015625 7.375 0.015625 6C0.015625 4.625 0.5 3.45312 1.46875 2.48438C2.4375 1.48438 3.60938 0.984375 4.98438 0.984375H9.01562V2.90625H4.98438C4.14062 2.90625 3.40625 3.21875 2.78125 3.84375Z" fill="#5F9F84"></path>
                  </svg>
                  {{ article.title }}
                </a></li>

              {% endfor %}

            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

backend/templates/private/courses.html
{% extends 'private/_base.html' %}

{% load static %}

{% block og_title %}
  {% block title %}Все курсы | {{ block.super }}{% endblock %}
{% endblock %}

{% block content %}

  <h1 class="visually-hidden">Все курсы</h1>

  <div class="personalArea-content">
    <div class="courses">

      {% for course in object_list %}
        <div class="courses-col">
          <a href="{% url 'private_side:course_detail' course.pk %}" class="courses-wrap">
            <div class="courses-img">
              <img src="{{ course.image.url }}" alt="{{ course.title }}">
            </div>
            <div class="courses-info">
              <span class="courses-name">{{ course.title }}</span>
            </div>
          </a>
        </div>
      {% empty %}
        <div class="courses-col">Нет курсов</div>
      {% endfor %}

    </div>
  </div>
{% endblock %}

backend/templates/private/index_student.html
{% load static private_side_extras course_extras paid_course_extras %}

<div class="personalArea-content">

  {% for free_lesson in free_lessons %}

    <div class="personalArea-block">
      <div class="personalArea-balance__img">
        <img src="{% static 'img/balance0img.svg' %}" alt="">
      </div>

      <div class="personalArea-block__top">
        <span class="personalArea-block__title">Пробное занятие</span>
        <div class="personalArea-block__top-b"></div>
      </div>

      <div class="personalArea-balance">
        <div class="personalArea-balance__info">

          {% if free_lesson.datetime %}
            <p>Занятие запланировано на <span>{{ free_lesson.datetime }}</span></p>
          {% else %}
            <p>Занятие ещё не внесли в расписание.</p>
          {% endif %}

        </div>

        <a href="{% url 'private_side:courses' %}" class="main-btn">Оплатить занятия</a>

      </div>
    </div>

  {% endfor %}

  {% for group_courses_stat in groups_courses_stat %}

    <div class="personalArea-block">
      <div class="personalArea-block__top">
        <span class="personalArea-block__title">Баланс по направлению {{ group_courses_stat.title }}</span>
        <div class="personalArea-block__top-b"></div>
      </div>

      <div class="personalArea-balance">
        <div class="personalArea-balance__info">

          <p>У Вас <span>{{ group_courses_stat.lessons }}</span> занятий</p>

          {% if group_courses_stat.bonus %}
            <p>Из них <span>{{ group_courses_stat.bonus }}</span> бонусных</p>
          {% endif %}

          <p>Срок завершения <span>{{ group_courses_stat.valid_until|date }}</span></p>

        </div>

        <a href="{% url 'private_side:courses' %}" class="main-btn">Оплатить занятия</a>

        <div class="personalArea-balance__img">
          <img src="{% static 'img/balance0img.svg' %}" alt="">
        </div>
      </div>
    </div>

  {% endfor %}

  {#  {% if object_list %}#}
  {##}
  {#    {% with active_paid_course=object_list|first %}#}
  {##}
  {#      <div class="personalArea-block">#}
  {#        <div class="personalArea-block__top">#}
  {#          <span class="personalArea-block__title">Статистика</span>#}
  {#          <div class="personalArea-block__top-b"></div>#}
  {#        </div>#}
  {#        <div class="personalArea-statistics__row">#}
  {#          <div class="personalArea-statistics__col">#}
  {#            <div class="personalArea-statistics__circle">#}
  {#              <div class="personalArea-statistics__ico" id="perstatistics1"></div>#}
  {#              <div class="personalArea-statistics__hidden" id="perstatistics1-1">5</div>#}
  {#              <div class="personalArea-statistics__hidden" id="perprocent-1">0.94</div>#}
  {#            </div>#}
  {#            <span class="personalArea-statistics__subtitle">Средний бал за задания</span>#}
  {#          </div>#}
  {##}
  {#          <div class="personalArea-statistics__col">#}
  {#            <div class="personalArea-statistics__circle">#}
  {#              <div class="personalArea-statistics__ico" id="perstatistics2"></div>#}
  {#              <div class="personalArea-statistics__hidden" id="perstatistics2-2">5</div>#}
  {#              <div class="personalArea-statistics__hidden" id="perprocent-2">#}
  {#                {{ active_paid_course.paid_course_lessons.all|get_statistic_result:'test_result' }}#}
  {#              </div>#}
  {#            </div>#}
  {#            <span class="personalArea-statistics__subtitle">Средний бал за тесты</span>#}
  {#          </div>#}
  {##}
  {#          <div class="personalArea-statistics__col">#}
  {#            <div class="personalArea-statistics__circle">#}
  {#              <div class="personalArea-statistics__ico" id="perstatistics3"></div>#}
  {#              <div class="personalArea-statistics__hidden" id="perstatistics3-3">5</div>#}
  {#              <div class="personalArea-statistics__hidden" id="perprocent-3">0.94</div>#}
  {#            </div>#}
  {#            <span class="personalArea-statistics__subtitle">Средний бал за игры</span>#}
  {#          </div>#}
  {#        </div>#}
  {#      </div>#}
  {##}
  {#      <div class="personalArea-block">#}
  {#        <div class="personalArea-block__top">#}
  {#          <span class="personalArea-block__title">Текущий курс</span>#}
  {#          <div class="personalArea-block__top-b"></div>#}
  {#        </div>#}
  {#        <div class="personalArea-course">#}
  {#          <div class="personalArea-course__col">#}
  {#            <h3 class="personalArea-course__title">{{ active_paid_course }}</h3>#}
  {#            <ul>#}
  {#              <li>Пройдено уроков: <span>{{ active_paid_course.paid_course_lessons|finished:1|filter_count }} из {{ active_paid_course.course.courselesson_set.count }}</span></li>#}
  {##}
  {#              <li>До конца курса осталось: <span>~3 месяца</span></li>#}
  {##}
  {#            </ul>#}
  {#          </div>#}
  {#          <div class="personalArea-course__col">#}
  {#            <h3 class="personalArea-course__title">Преподаватель</h3>#}
  {#            <div class="personalArea-course__user">#}
  {#              <div class="personalArea-course__user-img">#}
  {#                <img src="{% static 'img/videoCall-user.svg' %}" alt="">#}
  {#              </div>#}
  {#              <div class="personalArea-course__user-info">#}
  {#                <span class="personalArea-course__name">{{ active_paid_course.teacher }}</span>#}
  {#                <a href="#" class="personalArea-course__link">Посмотреть профиль</a>#}
  {#              </div>#}
  {#            </div>#}
  {#          </div>#}
  {#        </div>#}
  {#      </div>#}
  {##}
  {#      <div class="personalArea-block">#}
  {#        <div class="personalArea-block__top">#}
  {#          <span class="personalArea-block__title">Текущее домашнее задание</span>#}
  {#          <div class="personalArea-block__top-b"></div>#}
  {#        </div>#}
  {#        <div class="personalArea-slider__wrap range-slider__wrap">#}
  {#          <div class="personalArea-slider range-slider">#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Притяжательный падеж существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>25 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Множественное число существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>28 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Упражнения на артикли</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>30 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Множественное число существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>28 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Притяжательный падеж существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>25 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#          </div>#}
  {#          <input type="range" class="range" min="1" value="1" step="1" max="5">#}
  {#        </div>#}
  {#      </div>#}
  {##}
  {#      <div class="personalArea-block">#}
  {#        <div class="personalArea-block__top personalArea-block__top-flex">#}
  {#          <span class="personalArea-block__title"><img src="{% static 'img/warning.svg' %}" alt="">Хвосты</span>#}
  {#          <div class="personalArea-block__top-b"></div>#}
  {#        </div>#}
  {#        <div class="personalArea-slider__wrap range-slider__wrap">#}
  {#          <div class="personalArea-slider range-slider">#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Притяжательный падеж существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>25 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#            <div class="personalArea-slide">#}
  {#              <div class="lessonTopic">#}
  {#                <span class="lessonTopic-subtitle">Тема урока:</span>#}
  {#                <p><a href="#">Множественное число существительного.</a></p>#}
  {#                <div class="lessonTopic-bottom">#}
  {#                  <span class="lessonTopic-subtitle">Срок сдачи:</span>#}
  {#                  <p>28 мая 2020</p>#}
  {#                </div>#}
  {#              </div>#}
  {#            </div>#}
  {#          </div>#}
  {#          <input type="range" class="range" min="1" value="1" step="1" max="2">#}
  {#        </div>#}
  {#      </div>#}
  {##}
  {#    {% endwith %}#}

  {#  {% else %}#}
  {#    <div class="personalArea-block">#}
  {#      <div class="personalArea-block__top">#}
  {#        <span class="personalArea-block__title">#}
  {#          Рады Вас приветствовать на сайте!!!#}
  {#        </span>#}
  {#        <div class="personalArea-block__top-b"></div>#}
  {##}
  {#        <span>#}
  {#          Администратор скоро с Вами свяжется.#}
  {#        </span>#}
  {#      </div>#}
  {#    </div>#}

  {#  {% endif %}#}

</div>

backend/templates/private/index_teacher.html
{% load static %}

<div class="personalArea-content">
  <div class="personalArea-block">
    <div class="personalArea-block__top">
      <span class="personalArea-block__title">Занятия сегодня</span>
      <div class="personalArea-block__top-b"></div>
    </div>

    <div class="master">
      <div class="master-row">

        {% for schedule in timetable %}
          {% include 'private/components/lesson_item.html' %}
        {% endfor %}

      </div>
    </div>
  </div>
</div>

backend/templates/private/lessons.html
{% extends 'private/_base.html' %}

{% load static course_extras %}

{% block og_title %}
  {% block title %}Занятия | {{ block.super }}{% endblock %}
{% endblock %}

{% block content %}

  <h1 class="visually-hidden">Занятия</h1>

  <div class="personalArea-content">
    <div class="personalArea-block">
      <div class="personalArea-block__top">
        <span class="personalArea-block__title">Занятия сегодня</span>
        <div class="personalArea-block__top-b"></div>
      </div>

      <div class="master">
        <div class="master-row">

          {% for schedule in timetable %}
            {% include 'private/components/lesson_item.html' %}
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
{% endblock %}